### ISSUE TITLE
Incomplete Trajectory for higher altitudes

### ISSUE THREAD

**Issue by ankitpatel0698** [uataq/stilt#79]
Hi sir
I have run STILT at zagl <- 4000 meter altitude and 120 hour backward mode. And in the output i cant see a complete trajectory of footprints to the receptor (RED DOT). Is there any explanation of this incomplete trajectory for higher altitudes? or is it something like model incapability for higher altitudes?  Whereas we can see a complete trajectory of footprints for lower altitudes i.e. 100 meter in my run. Please clear my doubt.

4000 meter altitude output
![scot2017_4000E](https://user-images.githubusercontent.com/75941016/151506300-5644d12d-49be-4c5f-b63d-cc112c3b6d11.png)
![oot2017_4000E](https://user-images.githubusercontent.com/75941016/151506332-12f3695c-2048-4340-a195-f72051293794.png)

100 Meter altitude output
![scot2017_100E](https://user-images.githubusercontent.com/75941016/151506755-a17a6c59-4e2c-4017-9791-553c0c62579d.png)

**Comment by tartanrunner25** [comment]
Hello Ankit,

Looking at your simulations, it seems like everything checks out! The strength of the footprint is going to be a function of how many particles are located  within the planetary boundary layer (PBL). By releasing particles at 4000mAgL, chances are the PBL is much shallower than 4000mAGL. From my experience, typical PBL heights are around ~250-m over the ocean, therefore much shallower than the release height of 4000m. In this case, the footprint will be zero, assuming no trajectories drop below 250m. Given that the air flow over the ocean is relatively stratified, you probably won't see many particles go from 4000m and drop below the PBL height of ~250m within a short amount of time. Over time, as the particles "will" disperse vertically due to convective mixing, which is why you see higher footprints further away from the receptor. If you look carefully, the footprints are actually pretty high over land, likely due to convective mixing being especially vigorous over land, which entrains the particle into the PBL.

For the case where you release particles at 100m, almost all of your trajectories should _start within the PBL_, which will of course strengthen the footprint, locally. The footprint essentially measurements the sensitivity of upwind surface fluxes to concentration changes at your measurement site. If your particles are above the PBL, they can't really interact with surface fluxes, which is why the footprint is formulated in this way. An in-depth explanation of the footprint can be found here: https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2002JD003161

-Derek

**Comment by ankitpatel0698** [comment]
Sir, Thanks a lot for the explanation.
